### ISSUE TITLE
cmd/server folder is missing in tarballs

### ISSUE THREAD

**Issue by muhahacz** [LibreRead/LibreRead#22]
cmd/server folder is missing in tarballs. I am unable to compile server from https://github.com/LibreRead/server/archive/v1.0.0.tar.gz

**Comment by kpcyrd** [comment]
cmd/server was very recently introduced after 1.0.0, the file you're looking for is `server.go` directly in the project root. :)

**Comment by muhahacz** [comment]
I see. Seems there is an error.. See log.

`
FROM golang:alpine as builder
RUN apk add --no-cache musl-dev gcc git curl
RUN mkdir -p /go/src/github.com/LibreRead/server  && curl -sSL https://github.com/LibreRead/server/archive/v1.0.0.tar.gz | tar xz -C /go/src/github.com/LibreRead/server --strip-components=1 
WORKDIR /go/src/github.com/LibreRead/server
RUN go-wrapper download
RUN go-wrapper install
`

```

Log:
...
github.com/LibreRead/server
# github.com/LibreRead/server
./server.go:58:6: main redeclared in this block
	previous declaration at ./quote.go:26:6
```

**Comment by mysticmode** [comment]
Hey @muhahacz Sorry for that.

I just created a new release here https://github.com/LibreRead/server/releases/tag/v1.1.0

Quotation code is removed from this repo and we placed it in a separate repo. The release you are pulling is the older one. And that is the issue you are having now.

Could you pull from the lastest release I mentioned above? Thanks.
